---
# ansible playbook to setup a ubuntu development box
- hosts: localhost

  vars:
    ms_mirror: 'https://packages.microsoft.com'
    username: seb
    
  tasks:
  - name: Install base packages
    become: yes
    apt:
      name: [git,curl,wget,python3-pip,python3-venv,apt-transport-https,ca-certificates,software-properties-common]
      state: present
 
  - name: Install https://packages.microsoft.com key
    become: yes
    apt_key:
      url: '{{ ms_mirror }}/keys/microsoft.asc'
      state: present

  - name: Install Azure CLI repo
    become: yes
    apt_repository:
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli bionic main'
      filename: azure-cli
      state: present

  - name: Install Azure CLI 
    become: yes
    apt:
      name: azure-cli
      state: present
      update_cache: yes   

  - name: Install Powerline GO
    become: yes
    apt:
      name: powerline
      state: present

  - name: Configure Powerline GO in .bashrc
    blockinfile:
        path: "/home/{{ username }}/.bashrc"
        backup: yes 
        marker: "# {mark} Powerline configuration"
        state: present
        block: | 
          # Powerline configuration
          if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
            powerline-daemon -q
            POWERLINE_BASH_CONTINUATION=1
            POWERLINE_BASH_SELECT=1
            source /usr/share/powerline/bindings/bash/powerline.sh
          fi
...
