---
# ansible playbook to setup a ubuntu development box
- hosts: 192.168.122.73
  #- hosts: 127.0.0.1
  #connection: local

  vars:
    starship_version: '1.11.0'
    username: "{{ ansible_user_id }}"
  
  tasks:
  - name: Install specific git ppa repository
    become: true
    ansible.builtin.apt_repository:
      repo: ppa:git-core/ppa
      state: present
      filename: git
    tags: base

  - name: Install base packages
    become: true
    ansible.builtin.apt:
      name: [git, curl, wget, python3-pip, python3-venv, apt-transport-https, ca-certificates, software-properties-common, bzip2, unzip, tree, stow]
      state: present
    tags: base 

  - name: Install zsh
    become: true
    ansible.builtin.apt:
      name: zsh
      state: present
    tags: 
    - base
    - zsh

  - name: Setup zsh as default shell for user {{ username }}
    become: true
    ansible.builtin.user:
      name: "{{ username }}"
      shell: /usr/bin/zsh
    tags: 
    - base
    - zsh

  - name: Add Docker apt key - new method
    become: true
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: 0644
      force: true
    when: ansible_facts['distribution_major_version'] | int >= 22 # Should not run on WSL and Ubuntu > 22

  - name: Configure Docker apt repository
    become: true
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/docker.asc, arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      filename: docker
    when: ansible_facts['distribution_major_version'] | int >= 22 # Should not run on WSL or Ubuntu >= 22
    tags: docker

  - name: Install Docker
    become: true
    ansible.builtin.apt:
      name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
    tags: docker

  - name: Add user {{ username }} to docker group
    become: true
    ansible.builtin.user:
      name: "{{ username }}"
      append: true
      groups: 
      - docker
    tags: docker


  - name: Download and install starship.rs
    become: true
    ansible.builtin.unarchive:
      src: https://github.com/starship/starship/releases/download/v{{ starship_version }}/starship-x86_64-unknown-linux-gnu.tar.gz
      dest: /usr/local/bin
      remote_src: true
      mode: 0755
    tags:
    - base
    - starship
    - zsh

  - name: git checkout dotfiles
    ansible.builtin.git:
      repo: 'https://github.com/pondichys/.dotfiles.git'
      dest: "/home/{{ username }}/.dotfiles"
    tags:
    - dotfiles
  - name: set dotfiles
    ansible.builtin.shell:
      chdir: "/home/{{ username}}/.dotfiles"
      cmd: "for DOT in zsh starship;do stow $DOT; done"
    tags:
    - dotfiles

  - name: install latest distrobox
    become: true
    ansible.builtin.shell:
      cmd: "curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh"

...
